//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445_Assignment5.bitcoinService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bitcoinService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createAccount", ReplyAction="*")]
        CSE445_Assignment5.bitcoinService.createAccountResponse createAccount(CSE445_Assignment5.bitcoinService.createAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.createAccountResponse> createAccountAsync(CSE445_Assignment5.bitcoinService.createAccountRequest request);
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signIn", ReplyAction="*")]
        CSE445_Assignment5.bitcoinService.signInResponse signIn(CSE445_Assignment5.bitcoinService.signInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signIn", ReplyAction="*")]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.signInResponse> signInAsync(CSE445_Assignment5.bitcoinService.signInRequest request);
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/viewBalance", ReplyAction="*")]
        CSE445_Assignment5.bitcoinService.viewBalanceResponse viewBalance(CSE445_Assignment5.bitcoinService.viewBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/viewBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.viewBalanceResponse> viewBalanceAsync(CSE445_Assignment5.bitcoinService.viewBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBalance", ReplyAction="*")]
        CSE445_Assignment5.bitcoinService.addBalanceResponse addBalance(CSE445_Assignment5.bitcoinService.addBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.addBalanceResponse> addBalanceAsync(CSE445_Assignment5.bitcoinService.addBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/withdrawBalance", ReplyAction="*")]
        CSE445_Assignment5.bitcoinService.withdrawBalanceResponse withdrawBalance(CSE445_Assignment5.bitcoinService.withdrawBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/withdrawBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.withdrawBalanceResponse> withdrawBalanceAsync(CSE445_Assignment5.bitcoinService.withdrawBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAccount", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.createAccountRequestBody Body;
        
        public createAccountRequest() {
        }
        
        public createAccountRequest(CSE445_Assignment5.bitcoinService.createAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public createAccountRequestBody() {
        }
        
        public createAccountRequestBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.createAccountResponseBody Body;
        
        public createAccountResponse() {
        }
        
        public createAccountResponse(CSE445_Assignment5.bitcoinService.createAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createAccountResult;
        
        public createAccountResponseBody() {
        }
        
        public createAccountResponseBody(string createAccountResult) {
            this.createAccountResult = createAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signIn", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.signInRequestBody Body;
        
        public signInRequest() {
        }
        
        public signInRequest(CSE445_Assignment5.bitcoinService.signInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public signInRequestBody() {
        }
        
        public signInRequestBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signInResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.signInResponseBody Body;
        
        public signInResponse() {
        }
        
        public signInResponse(CSE445_Assignment5.bitcoinService.signInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signInResult;
        
        public signInResponseBody() {
        }
        
        public signInResponseBody(string signInResult) {
            this.signInResult = signInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class viewBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="viewBalance", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.viewBalanceRequestBody Body;
        
        public viewBalanceRequest() {
        }
        
        public viewBalanceRequest(CSE445_Assignment5.bitcoinService.viewBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class viewBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cookie;
        
        public viewBalanceRequestBody() {
        }
        
        public viewBalanceRequestBody(string account, string password, string cookie) {
            this.account = account;
            this.password = password;
            this.cookie = cookie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class viewBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="viewBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.viewBalanceResponseBody Body;
        
        public viewBalanceResponse() {
        }
        
        public viewBalanceResponse(CSE445_Assignment5.bitcoinService.viewBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class viewBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSE445_Assignment5.bitcoinService.ArrayOfString viewBalanceResult;
        
        public viewBalanceResponseBody() {
        }
        
        public viewBalanceResponseBody(CSE445_Assignment5.bitcoinService.ArrayOfString viewBalanceResult) {
            this.viewBalanceResult = viewBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBalance", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.addBalanceRequestBody Body;
        
        public addBalanceRequest() {
        }
        
        public addBalanceRequest(CSE445_Assignment5.bitcoinService.addBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cookie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double amount;
        
        public addBalanceRequestBody() {
        }
        
        public addBalanceRequestBody(string account, string password, string cookie, double amount) {
            this.account = account;
            this.password = password;
            this.cookie = cookie;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.addBalanceResponseBody Body;
        
        public addBalanceResponse() {
        }
        
        public addBalanceResponse(CSE445_Assignment5.bitcoinService.addBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSE445_Assignment5.bitcoinService.ArrayOfString addBalanceResult;
        
        public addBalanceResponseBody() {
        }
        
        public addBalanceResponseBody(CSE445_Assignment5.bitcoinService.ArrayOfString addBalanceResult) {
            this.addBalanceResult = addBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class withdrawBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="withdrawBalance", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.withdrawBalanceRequestBody Body;
        
        public withdrawBalanceRequest() {
        }
        
        public withdrawBalanceRequest(CSE445_Assignment5.bitcoinService.withdrawBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class withdrawBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cookie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double amount;
        
        public withdrawBalanceRequestBody() {
        }
        
        public withdrawBalanceRequestBody(string account, string password, string cookie, double amount) {
            this.account = account;
            this.password = password;
            this.cookie = cookie;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class withdrawBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="withdrawBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSE445_Assignment5.bitcoinService.withdrawBalanceResponseBody Body;
        
        public withdrawBalanceResponse() {
        }
        
        public withdrawBalanceResponse(CSE445_Assignment5.bitcoinService.withdrawBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class withdrawBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSE445_Assignment5.bitcoinService.ArrayOfString withdrawBalanceResult;
        
        public withdrawBalanceResponseBody() {
        }
        
        public withdrawBalanceResponseBody(CSE445_Assignment5.bitcoinService.ArrayOfString withdrawBalanceResult) {
            this.withdrawBalanceResult = withdrawBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CSE445_Assignment5.bitcoinService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CSE445_Assignment5.bitcoinService.WebService1Soap>, CSE445_Assignment5.bitcoinService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSE445_Assignment5.bitcoinService.createAccountResponse CSE445_Assignment5.bitcoinService.WebService1Soap.createAccount(CSE445_Assignment5.bitcoinService.createAccountRequest request) {
            return base.Channel.createAccount(request);
        }
        
        public string createAccount(string account, string password) {
            CSE445_Assignment5.bitcoinService.createAccountRequest inValue = new CSE445_Assignment5.bitcoinService.createAccountRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.createAccountRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            CSE445_Assignment5.bitcoinService.createAccountResponse retVal = ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).createAccount(inValue);
            return retVal.Body.createAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.createAccountResponse> CSE445_Assignment5.bitcoinService.WebService1Soap.createAccountAsync(CSE445_Assignment5.bitcoinService.createAccountRequest request) {
            return base.Channel.createAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.createAccountResponse> createAccountAsync(string account, string password) {
            CSE445_Assignment5.bitcoinService.createAccountRequest inValue = new CSE445_Assignment5.bitcoinService.createAccountRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.createAccountRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).createAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSE445_Assignment5.bitcoinService.signInResponse CSE445_Assignment5.bitcoinService.WebService1Soap.signIn(CSE445_Assignment5.bitcoinService.signInRequest request) {
            return base.Channel.signIn(request);
        }
        
        public string signIn(string account, string password) {
            CSE445_Assignment5.bitcoinService.signInRequest inValue = new CSE445_Assignment5.bitcoinService.signInRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.signInRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            CSE445_Assignment5.bitcoinService.signInResponse retVal = ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).signIn(inValue);
            return retVal.Body.signInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.signInResponse> CSE445_Assignment5.bitcoinService.WebService1Soap.signInAsync(CSE445_Assignment5.bitcoinService.signInRequest request) {
            return base.Channel.signInAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.signInResponse> signInAsync(string account, string password) {
            CSE445_Assignment5.bitcoinService.signInRequest inValue = new CSE445_Assignment5.bitcoinService.signInRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.signInRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).signInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSE445_Assignment5.bitcoinService.viewBalanceResponse CSE445_Assignment5.bitcoinService.WebService1Soap.viewBalance(CSE445_Assignment5.bitcoinService.viewBalanceRequest request) {
            return base.Channel.viewBalance(request);
        }
        
        public CSE445_Assignment5.bitcoinService.ArrayOfString viewBalance(string account, string password, string cookie) {
            CSE445_Assignment5.bitcoinService.viewBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.viewBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.viewBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            CSE445_Assignment5.bitcoinService.viewBalanceResponse retVal = ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).viewBalance(inValue);
            return retVal.Body.viewBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.viewBalanceResponse> CSE445_Assignment5.bitcoinService.WebService1Soap.viewBalanceAsync(CSE445_Assignment5.bitcoinService.viewBalanceRequest request) {
            return base.Channel.viewBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.viewBalanceResponse> viewBalanceAsync(string account, string password, string cookie) {
            CSE445_Assignment5.bitcoinService.viewBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.viewBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.viewBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            return ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).viewBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSE445_Assignment5.bitcoinService.addBalanceResponse CSE445_Assignment5.bitcoinService.WebService1Soap.addBalance(CSE445_Assignment5.bitcoinService.addBalanceRequest request) {
            return base.Channel.addBalance(request);
        }
        
        public CSE445_Assignment5.bitcoinService.ArrayOfString addBalance(string account, string password, string cookie, double amount) {
            CSE445_Assignment5.bitcoinService.addBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.addBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.addBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            inValue.Body.amount = amount;
            CSE445_Assignment5.bitcoinService.addBalanceResponse retVal = ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).addBalance(inValue);
            return retVal.Body.addBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.addBalanceResponse> CSE445_Assignment5.bitcoinService.WebService1Soap.addBalanceAsync(CSE445_Assignment5.bitcoinService.addBalanceRequest request) {
            return base.Channel.addBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.addBalanceResponse> addBalanceAsync(string account, string password, string cookie, double amount) {
            CSE445_Assignment5.bitcoinService.addBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.addBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.addBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            inValue.Body.amount = amount;
            return ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).addBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSE445_Assignment5.bitcoinService.withdrawBalanceResponse CSE445_Assignment5.bitcoinService.WebService1Soap.withdrawBalance(CSE445_Assignment5.bitcoinService.withdrawBalanceRequest request) {
            return base.Channel.withdrawBalance(request);
        }
        
        public CSE445_Assignment5.bitcoinService.ArrayOfString withdrawBalance(string account, string password, string cookie, double amount) {
            CSE445_Assignment5.bitcoinService.withdrawBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.withdrawBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.withdrawBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            inValue.Body.amount = amount;
            CSE445_Assignment5.bitcoinService.withdrawBalanceResponse retVal = ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).withdrawBalance(inValue);
            return retVal.Body.withdrawBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.withdrawBalanceResponse> CSE445_Assignment5.bitcoinService.WebService1Soap.withdrawBalanceAsync(CSE445_Assignment5.bitcoinService.withdrawBalanceRequest request) {
            return base.Channel.withdrawBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSE445_Assignment5.bitcoinService.withdrawBalanceResponse> withdrawBalanceAsync(string account, string password, string cookie, double amount) {
            CSE445_Assignment5.bitcoinService.withdrawBalanceRequest inValue = new CSE445_Assignment5.bitcoinService.withdrawBalanceRequest();
            inValue.Body = new CSE445_Assignment5.bitcoinService.withdrawBalanceRequestBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.cookie = cookie;
            inValue.Body.amount = amount;
            return ((CSE445_Assignment5.bitcoinService.WebService1Soap)(this)).withdrawBalanceAsync(inValue);
        }
    }
}
